sudo: required
services: 
        - docker

before_install: 
        - docker build -t jaskeerat/docker-react -f dev.Dockerfile .

script: 
        - docker run -e CI=true jaskeerat/docker-react npm run test

